Repository sb01-team10/sb01-otboo-team10, pull requests merged in 2025-06, with the labels that each got.

#5 Fix: Coderabbit 리뷰 반영 및 오타 수정
  .github/ISSUE_TEMPLATE/♻️Refactor.yml
  .github/ISSUE_TEMPLATE/🐞bug.yml
  .github/ISSUE_TEMPLATE/🔧chore.yml
  .github/ISSUE_TEMPLATE/🚀deploy.yml
  .github/workflows/create-issue-with-branch.yml
  codecov.yml
Labels: 🐛 bug

#14 Feat: User, Location 엔티티 추가 #12
  build.gradle
  src/main/java/com/codeit/weatherwear/location/entity/Location.java
  src/main/java/com/codeit/weatherwear/location/repository/LocationRepository.java
  src/main/java/com/codeit/weatherwear/user/entity/Gender.java
  src/main/java/com/codeit/weatherwear/user/entity/OAuthProvider.java
  src/main/java/com/codeit/weatherwear/user/entity/Role.java
  src/main/java/com/codeit/weatherwear/user/entity/User.java
  src/main/java/com/codeit/weatherwear/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: feat

#17 Feat: JwtSession 엔티티 추가 #13
  src/main/java/com/codeit/weatherwear/global/config/JpaConfig.java
  src/main/java/com/codeit/weatherwear/security/entity/JwtSession.java
  src/main/java/com/codeit/weatherwear/security/repository/JwtSessionRepository.java
Labels: feat

#24 Fix: Codecov Workflow Script 관련 이슈 수정 #18
  .github/workflows/codecov-wf.yml
  .gitignore
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/codeit/weatherwear/WeatherwearApplicationTests.java
  src/test/java/com/codeit/weatherwear/feed/repository/FeedRepositoryTest.java
  src/test/java/com/codeit/weatherwear/global/config/NamedEnumAwareH2Dialect.java
  src/test/resources/application-test.yml
Labels: fix

#28 Feat: OOTD 관련 엔티티 세팅
  src/main/java/com/codeit/weatherwear/domain/feed/entity/Feed.java
  src/main/java/com/codeit/weatherwear/domain/feed/entity/FeedComment.java
  src/main/java/com/codeit/weatherwear/domain/feed/entity/FeedLike.java
  src/main/java/com/codeit/weatherwear/domain/feed/repository/FeedCommentRepository.java
  src/main/java/com/codeit/weatherwear/domain/feed/repository/FeedLikeRepository.java
  src/main/java/com/codeit/weatherwear/domain/feed/repository/FeedRepository.java
  src/main/java/com/codeit/weatherwear/domain/ootd/entity/Ootd.java
  src/main/java/com/codeit/weatherwear/domain/ootd/entity/OotdClothes.java
  src/main/java/com/codeit/weatherwear/domain/ootd/repository/OotdClothesRepository.java
  src/main/java/com/codeit/weatherwear/domain/ootd/repository/OotdRepository.java
  src/test/java/com/codeit/weatherwear/feed/repository/FeedRepositoryTest.java
Labels: feat

#30 Feat: 사용자, 프로필 API
  build.gradle
  src/main/java/com/codeit/weatherwear/domain/location/dto/LocationDto.java
  src/main/java/com/codeit/weatherwear/domain/location/entity/Location.java
  src/main/java/com/codeit/weatherwear/domain/location/mapper/LocationMapper.java
  src/main/java/com/codeit/weatherwear/domain/location/repository/LocationRepository.java
  src/main/java/com/codeit/weatherwear/domain/security/entity/JwtSession.java
  src/main/java/com/codeit/weatherwear/domain/security/repository/JwtSessionRepository.java
  src/main/java/com/codeit/weatherwear/domain/user/controller/UserController.java
  src/main/java/com/codeit/weatherwear/domain/user/dto/request/ProfileUpdateRequest.java
  src/main/java/com/codeit/weatherwear/domain/user/dto/request/UserCreateRequest.java
  src/main/java/com/codeit/weatherwear/domain/user/dto/request/UserLockUpdateRequest.java
  src/main/java/com/codeit/weatherwear/domain/user/dto/response/ProfileDto.java
  src/main/java/com/codeit/weatherwear/domain/user/dto/response/UserDto.java
  src/main/java/com/codeit/weatherwear/domain/user/entity/Gender.java
  src/main/java/com/codeit/weatherwear/domain/user/entity/OAuthProvider.java
  src/main/java/com/codeit/weatherwear/domain/user/entity/Role.java
  src/main/java/com/codeit/weatherwear/domain/user/entity/User.java
  src/main/java/com/codeit/weatherwear/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/com/codeit/weatherwear/domain/user/exception/UserNotFoundException.java
  src/main/java/com/codeit/weatherwear/domain/user/mapper/UserMapper.java
  src/main/java/com/codeit/weatherwear/domain/user/repository/UserRepository.java
  src/main/java/com/codeit/weatherwear/domain/user/service/UserService.java
  src/main/java/com/codeit/weatherwear/domain/user/service/UserServiceImpl.java
  src/main/java/com/codeit/weatherwear/global/exception/ErrorCode.java
  src/main/java/com/codeit/weatherwear/user/entity/Role.java
  src/test/java/com/codeit/weatherwear/domain/user/service/UserServiceImplTest.java
Labels: feat

#34 Fix: Import 오류 해결 #33
  src/main/java/com/codeit/weatherwear/domain/directmessage/DirectMessage.java
  src/main/java/com/codeit/weatherwear/domain/feed/entity/Feed.java
  src/main/java/com/codeit/weatherwear/domain/feed/entity/FeedComment.java
  src/main/java/com/codeit/weatherwear/domain/feed/entity/FeedLike.java
  src/main/java/com/codeit/weatherwear/domain/follow/Follow.java
Labels: fix

#39 Feat: Feed API에 필요한 DTO 추가 #38
  src/main/java/com/codeit/weatherwear/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/codeit/weatherwear/domain/feed/dto/request/FeedUpdateRequest.java
  src/main/java/com/codeit/weatherwear/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/weatherwear/domain/ootd/dto/response/OotdDto.java
  src/main/java/com/codeit/weatherwear/domain/user/dto/response/AuthorDto.java
  src/main/java/com/codeit/weatherwear/domain/weather/dto/response/PrecipitationDto.java
  src/main/java/com/codeit/weatherwear/domain/weather/dto/response/TemperatureDto.java
  src/main/java/com/codeit/weatherwear/domain/weather/dto/response/WeatherSummaryDto.java
Labels: feat

#45 Feat: Feed API 틀 세팅
  build.gradle
  src/main/java/com/codeit/weatherwear/domain/feed/controller/FeedController.java
  src/main/java/com/codeit/weatherwear/domain/feed/dto/request/FeedCreateRequest.java
  src/main/java/com/codeit/weatherwear/domain/feed/dto/response/FeedDto.java
  src/main/java/com/codeit/weatherwear/domain/feed/entity/Feed.java
  src/main/java/com/codeit/weatherwear/domain/feed/service/FeedService.java
  src/main/java/com/codeit/weatherwear/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/codeit/weatherwear/domain/ootd/entity/OotdClothes.java
  src/main/java/com/codeit/weatherwear/domain/user/dto/response/AuthorDto.java
  src/main/java/com/codeit/weatherwear/domain/weather/dto/response/PrecipitationDto.java
  src/main/java/com/codeit/weatherwear/domain/weather/dto/response/WeatherSummaryDto.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/PrecipitationsType.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/SkyStatus.java
  src/test/java/com/codeit/weatherwear/domain/feed/service/impl/FeedServiceImplTest.java
Labels: feat, refactor, chore, test

#51 Feat: Follow 조회 API 개발
  src/main/java/com/codeit/weatherwear/domain/follow/Follow.java
  src/main/java/com/codeit/weatherwear/domain/follow/FollowController.java
  src/main/java/com/codeit/weatherwear/domain/follow/FollowService.java
  src/main/java/com/codeit/weatherwear/domain/follow/dto/FollowDto.java
  src/main/java/com/codeit/weatherwear/domain/follow/repository/FollowRepository.java
  src/main/java/com/codeit/weatherwear/domain/follow/repository/FollowRepositoryCustom.java
  src/main/java/com/codeit/weatherwear/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/codeit/weatherwear/global/response/PageResponse.java
  src/test/java/com/codeit/weatherwear/domain/follow/FollowRepositoryTest.java
  src/test/resources/application-test.yml
Labels: feat, test

#53 Feat: Jwt 토큰 발급 기본 로직 구현
  build.gradle
  src/main/java/com/codeit/weatherwear/domain/security/config/PropertiesConfig.java
  src/main/java/com/codeit/weatherwear/domain/security/config/SecurityConfig.java
  src/main/java/com/codeit/weatherwear/domain/security/config/TimeConfig.java
  src/main/java/com/codeit/weatherwear/domain/security/config/properties/JwtProperties.java
  src/main/java/com/codeit/weatherwear/domain/security/config/properties/TimeProperties.java
  src/main/java/com/codeit/weatherwear/domain/security/entity/JwtSession.java
  src/main/java/com/codeit/weatherwear/domain/security/service/JwtSessionService.java
  src/main/java/com/codeit/weatherwear/domain/user/init/AdminUserInitializer.java
  src/main/java/com/codeit/weatherwear/domain/user/service/UserServiceImpl.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/codeit/weatherwear/domain/clothes/controller/AttributesControllerTest.java
  src/test/java/com/codeit/weatherwear/domain/user/init/AdminUserInitializerTest.java
  src/test/java/com/codeit/weatherwear/domain/user/service/UserServiceImplTest.java
Labels: feat, refactor, chore, test

#60 🐛Bug: 속성 조회 서비스 에러 해결 & 조회조건 dto적용
  src/main/java/com/codeit/weatherwear/domain/clothes/controller/AttributesController.java
  src/main/java/com/codeit/weatherwear/domain/clothes/controller/api/AttributesApi.java
  src/main/java/com/codeit/weatherwear/domain/clothes/dto/request/AttributesSearchRequest.java
  src/main/java/com/codeit/weatherwear/domain/clothes/service/AttributesService.java
  src/main/java/com/codeit/weatherwear/domain/clothes/service/AttributesServiceImpl.java
Labels: fix, refactor

#62 Refactor: Feed API 코드 리팩토링
  src/main/java/com/codeit/weatherwear/domain/feed/controller/FeedController.java
  src/main/java/com/codeit/weatherwear/domain/feed/exception/FeedNotFoundException.java
  src/main/java/com/codeit/weatherwear/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/codeit/weatherwear/domain/ootd/entity/Ootd.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/Humidity.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/Precipitation.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/PrecipitationsType.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/Temperature.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/Weather.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/WindSpeed.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/WindSpeedType.java
  src/main/java/com/codeit/weatherwear/global/exception/ErrorCode.java
  src/test/java/com/codeit/weatherwear/domain/feed/service/impl/FeedServiceImplTest.java
Labels: fix, refactor

#65 Refactor: Follow 생성 시 예외 처리 추가
  src/main/java/com/codeit/weatherwear/domain/follow/Follow.java
  src/main/java/com/codeit/weatherwear/domain/follow/FollowService.java
  src/main/java/com/codeit/weatherwear/domain/follow/exception/FollowDuplicatedException.java
  src/main/java/com/codeit/weatherwear/domain/follow/exception/SelfFollowNotAllowedException.java
  src/main/java/com/codeit/weatherwear/domain/follow/repository/FollowRepository.java
  src/main/java/com/codeit/weatherwear/domain/follow/repository/FollowRepositoryImpl.java
  src/main/java/com/codeit/weatherwear/domain/user/entity/User.java
  src/main/java/com/codeit/weatherwear/global/exception/ErrorCode.java
  src/main/java/com/codeit/weatherwear/global/exception/GlobalExceptionHandler.java
Labels: fix, feat, refactor

#63 Feat: 커스텀 인증 로그인 로직 #49
  src/main/java/com/codeit/weatherwear/domain/auth/dto/SignInRequest.java
  src/main/java/com/codeit/weatherwear/domain/security/config/SecurityConfig.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/CustomAuthenticationFailureHandler.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/CustomAuthenticationFilter.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/CustomAuthenticationSuccessHandler.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/CustomUserDetails.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/CustomUserDetailsService.java
  src/main/java/com/codeit/weatherwear/domain/security/service/JwtSessionService.java
  src/main/java/com/codeit/weatherwear/domain/user/init/AdminUserInitializer.java
  src/main/java/com/codeit/weatherwear/domain/user/repository/UserRepository.java
  src/main/resources/application-prod.yml
  src/test/java/com/codeit/weatherwear/domain/clothes/controller/AttributesControllerTest.java
  src/test/java/com/codeit/weatherwear/domain/user/init/AdminUserInitializerTest.java
  src/test/java/com/codeit/weatherwear/global/config/TestSecurityConfig.java
Labels: feat, refactor, chore, test

#69 Feat: Feed 조회 API 페이지네이션 적용 및 추가 리팩토링
  src/main/java/com/codeit/weatherwear/domain/feed/controller/FeedController.java
  src/main/java/com/codeit/weatherwear/domain/feed/dto/condition/FeedSearchCondition.java
  src/main/java/com/codeit/weatherwear/domain/feed/dto/request/FeedGetParamRequest.java
  src/main/java/com/codeit/weatherwear/domain/feed/repository/FeedCustomRepository.java
  src/main/java/com/codeit/weatherwear/domain/feed/repository/FeedRepository.java
  src/main/java/com/codeit/weatherwear/domain/feed/repository/impl/FeedCustomRepositoryImpl.java
  src/main/java/com/codeit/weatherwear/domain/feed/service/FeedService.java
  src/main/java/com/codeit/weatherwear/domain/feed/service/impl/FeedServiceImpl.java
  src/main/java/com/codeit/weatherwear/domain/weather/entity/PrecipitationsType.java
  src/test/java/com/codeit/weatherwear/domain/feed/repository/FeedRepositoryTest.java
  src/test/java/com/codeit/weatherwear/domain/feed/service/impl/FeedServiceImplTest.java
Labels: feat, refactor, test

#70 Feat: JWT 인증 필터 구현
  src/main/java/com/codeit/weatherwear/domain/security/config/SecurityConfig.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/CustomAuthenticationSuccessHandler.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/jwt/JwtAuthenticationFilter.java
  src/main/java/com/codeit/weatherwear/domain/security/customauthentication/jwt/JwtLogoutHandler.java
  src/main/java/com/codeit/weatherwear/domain/security/repository/JwtSessionRepository.java
  src/main/java/com/codeit/weatherwear/domain/security/service/JwtSessionService.java
Labels: feat, refactor, chore
